services:
      webapi:
        build:  
           context: .
           dockerfile: Dockerfile
        image: webapi_posgresql_v1
        ports:
           - "5003:80"
        environment:
           - ASPNETCORE_URLS=http://+:80
           - ASPNETCORE_ENVIRONMENT=Development
           - ConnectionsStrings__DefaultConnection=Host=postgreserver;username=postgres;password=NetcodeHub2024;database=MyDb; TrustServerCertificate=true;
        depends_on:
            - postgreserver

      postgreserver:
        image: postgres:latest
        environment:
          POSTGRES_DB: MyDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: NetcodeHub2024
        ports:
          - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
  default:
    name: my_custom_network 

volumes:
  pgdata:

        
        